# Generated by Django 5.0.6 on 2024-06-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_logintable_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='password1',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='password1',
            new_name='password2',
        ),
    ]
